version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - labeldetector
      - dataobject
    networks:
      - app-network

  labeldetector:
    container_name: labelDetector
    build:
      context: ./labelDetector
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - rethinkdb
    networks:
      - app-network

  dataobject:
    container_name: dataObject
    build:
      context: ./dataObject
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:latest
    ports:
      - "8081:8080"
      - "28015:28015"
    restart: always
    volumes:
      - rethinkdb_data:/data
    networks:
      - app-network

  gateway:
    container_name: gateway
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  rethinkdb_data:
