name: Workflow for CI/CD with GitHub Actions and run tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install main dependencies
      run: npm install

    - name: Install dataObject dependencies
      run: |
        cd dataObject
        npm install

    - name: Install labelDetector dependencies
      run: |
        cd labelDetector
        npm install

    - name: Start backend and frontend
      run: npm run dev:all &

    - name: Run backend tests
      run: npm test

    - name: Run frontend tests
      run: npm run test:frontend